//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyTimeMonitor
    {
        public string CriteriaDate { get; set; }
        public Nullable<System.DateTime> AttDate { get; set; }
        public Nullable<byte> CriteriaShiftID { get; set; }
        public string InLabelOne { get; set; }
        public string InLabelTwo { get; set; }
        public string InLabelThree { get; set; }
        public string InLabelFour { get; set; }
        public Nullable<int> InLabelOneValue { get; set; }
        public Nullable<int> InLabelTwoValue { get; set; }
        public Nullable<int> InLabelThreeValue { get; set; }
        public Nullable<int> InLabeFourValue { get; set; }
        public string OutLabelOne { get; set; }
        public string OutLabelTwo { get; set; }
        public string OutLabelThree { get; set; }
        public string OutLabelFour { get; set; }
        public Nullable<int> OutLabelOneValue { get; set; }
        public Nullable<int> OutLabelTwoValue { get; set; }
        public Nullable<int> OutLabelThreeValue { get; set; }
        public Nullable<int> OutLabeFourValue { get; set; }
        public string ShiftName { get; set; }
    }
}
