//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendanceSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDepartment
    {
        public Nullable<short> CompanyID { get; set; }
        public string DeptName { get; set; }
        public Nullable<short> DivID { get; set; }
        public short DeptID { get; set; }
        public string DivisionName { get; set; }
        public string CompName { get; set; }
    }
}
